apiVersion: v1
kind: Pod
metadata:
  name: minio-initializer
  namespace: platform
spec:
  containers:
  - name: initializer
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: minio
  restartPolicy: Never
